import 'package:internship/model/product.dart';

final List<Product> products = [
  Product(
    name: 'Derby Leather Shoes',
    image: 'images/derby_shoes.jpg',
    gender: 'Men\'s',
    price: 120,
    rating: 4.0,
  ),
  
  Product(
    name: 'Classic Sneakers',
    image: 'images/classic_sneakers_shoes.jpg',
    gender: 'Women\'s',
    price: 90,
    rating: 4.5,
  ),
  Product(
    name: 'Running Sport Shoes',
    image: 'images/running_sport_shoes.jpg',
    gender: 'Unisex',
    price: 150,
    rating: 4.7,
  ),
  Product(
    name: 'Women\'s Ballet Flats',
    image: 'images/ballet_flats.jpg',
    gender: 'Women\'s',
    price: 80,
    rating: 4.3,
  ),
  Product(
    name: 'Men\'s Casual Sneakers',
    image: 'images/casual_sneakers.jpg',
    gender: 'Men\'s',
    price: 90,
    rating: 4.2,
  ),
  Product(
  name: 'Women\'s Running Shoes',
  image: 'images/running_shoes.jpg',
  gender: 'Women\'s',
  price: 110,
  rating: 4.6,
  ),
  Product(
    name: 'Leather Loafers',
    image: 'images/leather_loafers.jpg',
    gender: 'Men\'s',
    price: 115,
    rating: 4.1,
  ),
  Product(
    name: 'Women\'s Sandals',
    image: 'images/sandals.jpg',
    gender: 'Women\'s',
    price: 70,
    rating: 3.9,
  ),
  Product(
    name: 'Men\'s Hiking Boots',
    image: 'images/hiking_boots.jpg',
    gender: 'Men\'s',
    price: 150,
    rating: 4.8,
  ),
  Product(
    name: 'Women\'s Ankle Boots',
    image: 'images/ankle_boots.jpg',
    gender: 'Women\'s',
    price: 140,
    rating: 4.4,
  ),
  Product(
    name: 'Men\'s Slip-On Shoes',
    image: 'images/slip_on_shoes.jpg',
    gender: 'Men\'s',
    price: 100,
    rating: 4.0,
  ),
   Product(
    name: 'Classic Sneakers',
    image: 'images/classic_sneakers_shoes.jpg',
    gender: 'Women\'s',
    price: 90,
    rating: 4.5,
  ),
  Product(
    name: 'Running Sport Shoes',
    image: 'images/running_sport_shoes.jpg',
    gender: 'Unisex',
    price: 150,
    rating: 4.7,
  ),
  Product(
    name: 'Women\'s Ballet Flats',
    image: 'images/ballet_flats.jpg',
    gender: 'Women\'s',
    price: 80,
    rating: 4.3,
  ),
  Product(
    name: 'Men\'s Casual Sneakers',
    image: 'images/casual_sneakers.jpg',
    gender: 'Men\'s',
    price: 90,
    rating: 4.2,
  ),
  Product(
  name: 'Women\'s Running Shoes',
  image: 'images/running_shoes.jpg',
  gender: 'Women\'s',
  price: 110,
  rating: 4.6,
  ),
  Product(
    name: 'Leather Loafers',
    image: 'images/leather_loafers.jpg',
    gender: 'Men\'s',
    price: 115,
    rating: 4.1,
  ),
  Product(
    name: 'Women\'s Sandals',
    image: 'images/sandals.jpg',
    gender: 'Women\'s',
    price: 70,
    rating: 3.9,
  ),
  Product(
    name: 'Men\'s Hiking Boots',
    image: 'images/hiking_boots.jpg',
    gender: 'Men\'s',
    price: 150,
    rating: 4.8,
  ),
  Product(
    name: 'Women\'s Ankle Boots',
    image: 'images/ankle_boots.jpg',
    gender: 'Women\'s',
    price: 140,
    rating: 4.4,
  ),
  Product(
    name: 'Men\'s Slip-On Shoes',
    image: 'images/slip_on_shoes.jpg',
    gender: 'Men\'s',
    price: 100,
    rating: 4.0,
  ),
];
